### ISSUE TITLE
Comparison to dropbox/mypy-protobuf

### ISSUE THREAD

**Issue by GrahamCampbell** [arachnys/protostub#2]
How does this package compare to https://github.com/dropbox/mypy-protobuf please, functionality wise. What was it about that package that made you decide to create this one, or was it just for fun because why not?

**Comment by MrSaints** [comment]
> @GrahamCampbell: What was it about that package that made you decide to create this one

Technicalities aside (which @wjh will probably be in a better position to talk about), when `protostub` was created, and used internally, it was long before the linked dropbox/mypy-protobuf was released as an open source project. And out-of-the-box, we had Python 3 support due to our internal source being mostly on Py3.
That being said, when @wjh original developed this, I believe he took inspiration from a comment made by Guido about how Dropbox was using their own mypy generator.

We didn't create it just for fun or to compete in terms of functionality. Though, with the latter, dropbox/mypy-protobuf arguably does it _better_ in terms of idiomatic code generation for protobuf since it relies on the plugin system, whereas, we simply ship ours as a separate binary.

I hope that answers your questions.

**Comment by MrSaints** [comment]
Oh, and we also ship the standalone generator on Docker Hub :) So you _don't need_ to have any Python dependencies to begin using it.

**Comment by ghost** [comment]
As @MrSaints said, we created this before Dropbox released theirs, which was based off of a comment Guido made about their internal tool - which became `mypy-protobuf`.

By the time Dropbox released theirs, we already had this - which is entirely standalone, and doesn't function as a plugin for protoc. The issues with this are that there may well be cases where protobuf code isn't properly handled, stubs not generated, and then type errors may show up erroneously. We do use this internally however, and so far that hasn't happened. It has also been tested quite thoroughly.

Otherwise, this is much simpler. It will just take a text input, and transform it to an output, without running `protoc` or anything else!

Let me know if you have any more questions.

**Comment by hazzadous** [comment]
No doubt others will have the same thought. @wjh worth adding something to the README so it's nice and prominent?

**Comment by GrahamCampbell** [comment]
Thank you everyone for the thorough replies. I'll let you know if I see any bugs.

**Comment by ghost** [comment]
I'll get something added to the README, hope this has cleared things up for you @GrahamCampbell!
